id: AD26D0458
title: 'Words of Truth: An Aspiration for the Spread of the Noble Gendenpa Tradition'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:42:01.773829
  last_modified_at: 2022-03-01 03:42:01.773837
